/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HPage;

import AppliancesAction.InputForm;
import PressStart.PressStart;
import java.awt.Color;
import java.awt.GradientPaint;
import java.text.MessageFormat;
import java.util.Collections;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttribute;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.util.PaintUtils;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author homer
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomePanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        electricFan4 = new javax.swing.JButton();
        airconSplit4 = new javax.swing.JButton();
        WashingMachine4 = new javax.swing.JButton();
        airconWindow4 = new javax.swing.JButton();
        ecToaster4 = new javax.swing.JButton();
        breadToaster4 = new javax.swing.JButton();
        ledBulb4 = new javax.swing.JButton();
        blower4 = new javax.swing.JButton();
        electricKettle4 = new javax.swing.JButton();
        electricIron4 = new javax.swing.JButton();
        fridge4 = new javax.swing.JButton();
        airFryer4 = new javax.swing.JButton();
        waterDispenser4 = new javax.swing.JButton();
        riceCooker4 = new javax.swing.JButton();
        electricStove4 = new javax.swing.JButton();
        vacuumCleaner4 = new javax.swing.JButton();
        showerHeater4 = new javax.swing.JButton();
        humidifier4 = new javax.swing.JButton();
        blender4 = new javax.swing.JButton();
        iceMaker4 = new javax.swing.JButton();
        phone4 = new javax.swing.JButton();
        laptop4 = new javax.swing.JButton();
        sandPress4 = new javax.swing.JButton();
        mosqKiller4 = new javax.swing.JButton();
        ovenToaster4 = new javax.swing.JButton();
        electricOven4 = new javax.swing.JButton();
        hairStraightener4 = new javax.swing.JButton();
        Tablet4 = new javax.swing.JButton();
        desktopPC4 = new javax.swing.JButton();
        dtMonitor4 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableValues = new javax.swing.JTable();
        homeButton = new javax.swing.JButton();
        statsButton = new javax.swing.JButton();
        LogoLabel1 = new javax.swing.JLabel();
        computeButton = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();
        Clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KuryentipEEd");
        setBackground(new java.awt.Color(255, 255, 204));
        setResizable(false);

        HomePanel.setBackground(new java.awt.Color(255, 255, 204));
        HomePanel.setPreferredSize(new java.awt.Dimension(1024, 768));

        jScrollPane6.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane6.setPreferredSize(new java.awt.Dimension(1024, 768));

        jPanel11.setBackground(new java.awt.Color(147, 225, 111));
        jPanel11.setForeground(new java.awt.Color(255, 255, 255));

        electricFan4.setBackground(new java.awt.Color(14, 49, 23));
        electricFan4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        electricFan4.setForeground(new java.awt.Color(255, 255, 255));
        electricFan4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/2.png"))); // NOI18N
        electricFan4.setText("<html><center>Electric<br>Fan</html>");
        electricFan4.setBorder(new javax.swing.border.MatteBorder(null));
        electricFan4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        electricFan4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        electricFan4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        electricFan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electricFan4electricFanActionPerformed(evt);
            }
        });

        airconSplit4.setBackground(new java.awt.Color(14, 49, 23));
        airconSplit4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        airconSplit4.setForeground(new java.awt.Color(255, 255, 255));
        airconSplit4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/1.png"))); // NOI18N
        airconSplit4.setText("<html><center>Aircon<br>Split<br>(1.5HP)</html>");
        airconSplit4.setBorder(new javax.swing.border.MatteBorder(null));
        airconSplit4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        airconSplit4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        airconSplit4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        airconSplit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airconSplit4airconSplitActionPerformed(evt);
            }
        });

        WashingMachine4.setBackground(new java.awt.Color(14, 49, 23));
        WashingMachine4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        WashingMachine4.setForeground(new java.awt.Color(255, 255, 255));
        WashingMachine4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/4.png"))); // NOI18N
        WashingMachine4.setText("<html>Washing<br>Machine</html>");
        WashingMachine4.setBorder(new javax.swing.border.MatteBorder(null));
        WashingMachine4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        WashingMachine4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        WashingMachine4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        WashingMachine4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WashingMachine4WashingMachineActionPerformed(evt);
            }
        });

        airconWindow4.setBackground(new java.awt.Color(14, 49, 23));
        airconWindow4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        airconWindow4.setForeground(new java.awt.Color(255, 255, 255));
        airconWindow4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/21.png"))); // NOI18N
        airconWindow4.setText("<html><center>Aircon<br>Window<br>(1.5HP)</html>");
        airconWindow4.setBorder(new javax.swing.border.MatteBorder(null));
        airconWindow4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        airconWindow4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        airconWindow4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        airconWindow4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airconWindow4airconWindowActionPerformed(evt);
            }
        });

        ecToaster4.setBackground(new java.awt.Color(14, 49, 23));
        ecToaster4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        ecToaster4.setForeground(new java.awt.Color(255, 255, 255));
        ecToaster4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/3.png"))); // NOI18N
        ecToaster4.setText("<html><center>Microwave<br>Oven</html>");
        ecToaster4.setBorder(new javax.swing.border.MatteBorder(null));
        ecToaster4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ecToaster4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ecToaster4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        ecToaster4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecToaster4ecToasterActionPerformed(evt);
            }
        });

        breadToaster4.setBackground(new java.awt.Color(14, 49, 23));
        breadToaster4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        breadToaster4.setForeground(new java.awt.Color(255, 255, 255));
        breadToaster4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/7.png"))); // NOI18N
        breadToaster4.setText("<html><center>Bread<br>Toaster</html>\n");
        breadToaster4.setBorder(new javax.swing.border.MatteBorder(null));
        breadToaster4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        breadToaster4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        breadToaster4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        breadToaster4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breadToaster4breadToasterActionPerformed(evt);
            }
        });

        ledBulb4.setBackground(new java.awt.Color(14, 49, 23));
        ledBulb4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        ledBulb4.setForeground(new java.awt.Color(255, 255, 255));
        ledBulb4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/5.png"))); // NOI18N
        ledBulb4.setText("LED Bulb");
        ledBulb4.setBorder(new javax.swing.border.MatteBorder(null));
        ledBulb4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ledBulb4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ledBulb4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        ledBulb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ledBulb4ledBulbActionPerformed(evt);
            }
        });

        blower4.setBackground(new java.awt.Color(14, 49, 23));
        blower4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        blower4.setForeground(new java.awt.Color(255, 255, 255));
        blower4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/8.png"))); // NOI18N
        blower4.setText("Blower");
        blower4.setBorder(new javax.swing.border.MatteBorder(null));
        blower4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        blower4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        blower4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        blower4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blower4blowerActionPerformed(evt);
            }
        });

        electricKettle4.setBackground(new java.awt.Color(14, 49, 23));
        electricKettle4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        electricKettle4.setForeground(new java.awt.Color(255, 255, 255));
        electricKettle4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/11.png"))); // NOI18N
        electricKettle4.setText("<html><center>Electric<br>Kettle</html>");
        electricKettle4.setBorder(new javax.swing.border.MatteBorder(null));
        electricKettle4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        electricKettle4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        electricKettle4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        electricKettle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electricKettle4electricKettleActionPerformed(evt);
            }
        });

        electricIron4.setBackground(new java.awt.Color(14, 49, 23));
        electricIron4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        electricIron4.setForeground(new java.awt.Color(255, 255, 255));
        electricIron4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/10.png"))); // NOI18N
        electricIron4.setText("<html><center>Electric<br>Iron</html>");
        electricIron4.setBorder(new javax.swing.border.MatteBorder(null));
        electricIron4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        electricIron4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        electricIron4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        electricIron4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electricIron4electricIronActionPerformed(evt);
            }
        });

        fridge4.setBackground(new java.awt.Color(14, 49, 23));
        fridge4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        fridge4.setForeground(new java.awt.Color(255, 255, 255));
        fridge4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/6.png"))); // NOI18N
        fridge4.setText("Fridge");
        fridge4.setBorder(new javax.swing.border.MatteBorder(null));
        fridge4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fridge4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fridge4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        fridge4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fridge4fridgeActionPerformed(evt);
            }
        });

        airFryer4.setBackground(new java.awt.Color(14, 49, 23));
        airFryer4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        airFryer4.setForeground(new java.awt.Color(255, 255, 255));
        airFryer4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/9.png"))); // NOI18N
        airFryer4.setText("Air Fryer");
        airFryer4.setBorder(new javax.swing.border.MatteBorder(null));
        airFryer4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        airFryer4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        airFryer4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        airFryer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airFryer4airFryerActionPerformed(evt);
            }
        });

        waterDispenser4.setBackground(new java.awt.Color(14, 49, 23));
        waterDispenser4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        waterDispenser4.setForeground(new java.awt.Color(255, 255, 255));
        waterDispenser4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/12.png"))); // NOI18N
        waterDispenser4.setText("<html><center>Water<br>Dispenser</html>");
        waterDispenser4.setBorder(new javax.swing.border.MatteBorder(null));
        waterDispenser4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        waterDispenser4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        waterDispenser4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        waterDispenser4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterDispenser4waterDispenserActionPerformed(evt);
            }
        });

        riceCooker4.setBackground(new java.awt.Color(14, 49, 23));
        riceCooker4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        riceCooker4.setForeground(new java.awt.Color(255, 255, 255));
        riceCooker4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/13.png"))); // NOI18N
        riceCooker4.setText("Rice Cooker\n");
        riceCooker4.setBorder(new javax.swing.border.MatteBorder(null));
        riceCooker4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        riceCooker4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        riceCooker4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        riceCooker4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riceCooker4riceCookerActionPerformed(evt);
            }
        });

        electricStove4.setBackground(new java.awt.Color(14, 49, 23));
        electricStove4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        electricStove4.setForeground(new java.awt.Color(255, 255, 255));
        electricStove4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/14.png"))); // NOI18N
        electricStove4.setText("<html><center>Electric<br>Stove</html>");
        electricStove4.setBorder(new javax.swing.border.MatteBorder(null));
        electricStove4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        electricStove4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        electricStove4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        electricStove4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electricStove4electricStoveActionPerformed(evt);
            }
        });

        vacuumCleaner4.setBackground(new java.awt.Color(14, 49, 23));
        vacuumCleaner4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        vacuumCleaner4.setForeground(new java.awt.Color(255, 255, 255));
        vacuumCleaner4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/15.png"))); // NOI18N
        vacuumCleaner4.setText("<html><center>Vacuum<br>Cleaner</html>");
        vacuumCleaner4.setBorder(new javax.swing.border.MatteBorder(null));
        vacuumCleaner4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        vacuumCleaner4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        vacuumCleaner4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        vacuumCleaner4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacuumCleaner4vacuumCleanerActionPerformed(evt);
            }
        });

        showerHeater4.setBackground(new java.awt.Color(14, 49, 23));
        showerHeater4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        showerHeater4.setForeground(new java.awt.Color(255, 255, 255));
        showerHeater4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/16.png"))); // NOI18N
        showerHeater4.setText("<html><center>Shower<br>Heater</html>");
        showerHeater4.setBorder(new javax.swing.border.MatteBorder(null));
        showerHeater4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        showerHeater4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        showerHeater4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        showerHeater4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showerHeater4showerHeaterActionPerformed(evt);
            }
        });

        humidifier4.setBackground(new java.awt.Color(14, 49, 23));
        humidifier4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        humidifier4.setForeground(new java.awt.Color(255, 255, 255));
        humidifier4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/17.png"))); // NOI18N
        humidifier4.setText("Humidifier");
        humidifier4.setBorder(new javax.swing.border.MatteBorder(null));
        humidifier4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        humidifier4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        humidifier4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        humidifier4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                humidifier4humidifierActionPerformed(evt);
            }
        });

        blender4.setBackground(new java.awt.Color(14, 49, 23));
        blender4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        blender4.setForeground(new java.awt.Color(255, 255, 255));
        blender4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/18.png"))); // NOI18N
        blender4.setText("Blender");
        blender4.setBorder(new javax.swing.border.MatteBorder(null));
        blender4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        blender4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        blender4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        blender4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blender4blenderActionPerformed(evt);
            }
        });

        iceMaker4.setBackground(new java.awt.Color(14, 49, 23));
        iceMaker4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        iceMaker4.setForeground(new java.awt.Color(255, 255, 255));
        iceMaker4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/19.png"))); // NOI18N
        iceMaker4.setText("Ice Maker");
        iceMaker4.setBorder(new javax.swing.border.MatteBorder(null));
        iceMaker4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        iceMaker4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iceMaker4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        iceMaker4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iceMaker4iceMakerActionPerformed(evt);
            }
        });

        phone4.setBackground(new java.awt.Color(14, 49, 23));
        phone4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        phone4.setForeground(new java.awt.Color(255, 255, 255));
        phone4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/24.png"))); // NOI18N
        phone4.setText("Phone");
        phone4.setBorder(new javax.swing.border.MatteBorder(null));
        phone4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        phone4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        phone4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        phone4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone4phoneActionPerformed(evt);
            }
        });

        laptop4.setBackground(new java.awt.Color(14, 49, 23));
        laptop4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        laptop4.setForeground(new java.awt.Color(255, 255, 255));
        laptop4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/23.png"))); // NOI18N
        laptop4.setText("Laptop");
        laptop4.setBorder(new javax.swing.border.MatteBorder(null));
        laptop4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        laptop4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        laptop4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        laptop4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laptop4laptopActionPerformed(evt);
            }
        });

        sandPress4.setBackground(new java.awt.Color(14, 49, 23));
        sandPress4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        sandPress4.setForeground(new java.awt.Color(255, 255, 255));
        sandPress4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/22.png"))); // NOI18N
        sandPress4.setText("<html><center>Sandwich<br>Press</html>");
        sandPress4.setBorder(new javax.swing.border.MatteBorder(null));
        sandPress4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sandPress4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sandPress4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        sandPress4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sandPress4sandPressActionPerformed(evt);
            }
        });

        mosqKiller4.setBackground(new java.awt.Color(14, 49, 23));
        mosqKiller4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        mosqKiller4.setForeground(new java.awt.Color(255, 255, 255));
        mosqKiller4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/20.png"))); // NOI18N
        mosqKiller4.setText("<html><center>Mosquito<br>Killer</html>");
        mosqKiller4.setBorder(new javax.swing.border.MatteBorder(null));
        mosqKiller4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mosqKiller4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mosqKiller4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        mosqKiller4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mosqKiller4mosqKillerActionPerformed(evt);
            }
        });

        ovenToaster4.setBackground(new java.awt.Color(14, 49, 23));
        ovenToaster4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        ovenToaster4.setForeground(new java.awt.Color(255, 255, 255));
        ovenToaster4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/28.png"))); // NOI18N
        ovenToaster4.setText("<html><center>Oven<br>Toaster</html>");
        ovenToaster4.setBorder(new javax.swing.border.MatteBorder(null));
        ovenToaster4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ovenToaster4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ovenToaster4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        ovenToaster4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ovenToaster4ovenToasterActionPerformed(evt);
            }
        });

        electricOven4.setBackground(new java.awt.Color(14, 49, 23));
        electricOven4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        electricOven4.setForeground(new java.awt.Color(255, 255, 255));
        electricOven4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/14.png"))); // NOI18N
        electricOven4.setText("<html><center>Electric<br>Oven</html>");
        electricOven4.setBorder(new javax.swing.border.MatteBorder(null));
        electricOven4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        electricOven4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        electricOven4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        electricOven4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electricOven4electricOvenActionPerformed(evt);
            }
        });

        hairStraightener4.setBackground(new java.awt.Color(14, 49, 23));
        hairStraightener4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        hairStraightener4.setForeground(new java.awt.Color(255, 255, 255));
        hairStraightener4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/26.png"))); // NOI18N
        hairStraightener4.setText("<html><center>Hair<br>Straightener</html>");
        hairStraightener4.setBorder(new javax.swing.border.MatteBorder(null));
        hairStraightener4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        hairStraightener4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hairStraightener4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        hairStraightener4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairStraightener4hairStraightenerActionPerformed(evt);
            }
        });

        Tablet4.setBackground(new java.awt.Color(14, 49, 23));
        Tablet4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        Tablet4.setForeground(new java.awt.Color(255, 255, 255));
        Tablet4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/25.png"))); // NOI18N
        Tablet4.setText("Tablet");
        Tablet4.setBorder(new javax.swing.border.MatteBorder(null));
        Tablet4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tablet4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tablet4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Tablet4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tablet4TabletActionPerformed(evt);
            }
        });

        desktopPC4.setBackground(new java.awt.Color(14, 49, 23));
        desktopPC4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        desktopPC4.setForeground(new java.awt.Color(255, 255, 255));
        desktopPC4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/29.png"))); // NOI18N
        desktopPC4.setText("<html><center>Desktop<br>Computer</html>");
        desktopPC4.setBorder(new javax.swing.border.MatteBorder(null));
        desktopPC4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        desktopPC4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        desktopPC4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        desktopPC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desktopPC4desktopPCActionPerformed(evt);
            }
        });

        dtMonitor4.setBackground(new java.awt.Color(14, 49, 23));
        dtMonitor4.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        dtMonitor4.setForeground(new java.awt.Color(255, 255, 255));
        dtMonitor4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/27.png"))); // NOI18N
        dtMonitor4.setText("<html><center>Desktop<br>Monitor</html>");
        dtMonitor4.setBorder(new javax.swing.border.MatteBorder(null));
        dtMonitor4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dtMonitor4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dtMonitor4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        dtMonitor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtMonitor4dtMonitorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(electricFan4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WashingMachine4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(airconWindow4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(airconSplit4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(ecToaster4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(breadToaster4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ledBulb4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blower4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(airFryer4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fridge4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(electricIron4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(electricKettle4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(waterDispenser4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(riceCooker4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(electricStove4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vacuumCleaner4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(showerHeater4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(humidifier4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blender4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iceMaker4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(mosqKiller4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sandPress4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laptop4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phone4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(Tablet4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hairStraightener4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(electricOven4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ovenToaster4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(desktopPC4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtMonitor4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(airconWindow4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(electricFan4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WashingMachine4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(airconSplit4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ledBulb4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ecToaster4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(breadToaster4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blower4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(electricIron4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(airFryer4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fridge4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(electricKettle4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(electricStove4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(waterDispenser4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(riceCooker4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vacuumCleaner4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(blender4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showerHeater4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(humidifier4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iceMaker4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(laptop4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mosqKiller4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sandPress4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(electricOven4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hairStraightener4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ovenToaster4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Tablet4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desktopPC4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtMonitor4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 144, Short.MAX_VALUE))
        );

        jScrollPane6.setViewportView(jPanel10);

        tableValues.setBackground(new java.awt.Color(147, 225, 111));
        tableValues.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tableValues.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        tableValues.setForeground(new java.awt.Color(0, 0, 0));
        tableValues.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appliance", "Frequency", "Price (day)", "Price (month)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableValues.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(tableValues);

        homeButton.setBackground(new java.awt.Color(26, 65, 32));
        homeButton.setFont(new java.awt.Font("Press Start 2P", 0, 14)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        statsButton.setBackground(new java.awt.Color(26, 65, 32));
        statsButton.setFont(new java.awt.Font("Press Start 2P", 0, 14)); // NOI18N
        statsButton.setForeground(new java.awt.Color(255, 255, 255));
        statsButton.setText("Statistics");
        statsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsButtonActionPerformed(evt);
            }
        });

        LogoLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/logo small.png"))); // NOI18N
        LogoLabel1.setFocusable(false);

        computeButton.setBackground(new java.awt.Color(26, 65, 32));
        computeButton.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        computeButton.setForeground(new java.awt.Color(255, 255, 255));
        computeButton.setText("Compute");
        computeButton.setBorder(new javax.swing.border.MatteBorder(null));
        computeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeButtonActionPerformed(evt);
            }
        });

        exportButton.setBackground(new java.awt.Color(26, 65, 32));
        exportButton.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        exportButton.setForeground(new java.awt.Color(255, 255, 255));
        exportButton.setText("Export as PDF");
        exportButton.setBorder(new javax.swing.border.MatteBorder(null));
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        Clear.setBackground(new java.awt.Color(26, 65, 32));
        Clear.setFont(new java.awt.Font("Press Start 2P", 0, 9)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("Clear");
        Clear.setBorder(new javax.swing.border.MatteBorder(null));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(statsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HomePanelLayout.createSequentialGroup()
                                .addComponent(computeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(exportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(statsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(computeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public static void addRowToJTable(Object[] dataRow) {
        DefaultTableModel model = (DefaultTableModel)tableValues.getModel();
        model.addRow(dataRow);
    }
    public void getSum() {
        double sum = 0;
        for (int i = 0; i < tableValues.getRowCount(); i++) {
            String pricesString = tableValues.getValueAt(i, 2).toString();
            String pricesStringConvertion = pricesString.replace(" pesos", "");
            double prices = Double.parseDouble(pricesStringConvertion);
            sum += prices;
            }
        double sum1 = 0;
            for (int j = 0; j < tableValues.getRowCount(); j++) {
                String pricesString = tableValues.getValueAt(j, 3).toString();
                String pricesStringConvertion = pricesString.replace(" pesos", "");
                double prices = Double.parseDouble(pricesStringConvertion);
                sum1 += prices;
                }
            
                String formattedSum = String.format("%.4f", sum);
                String sumString = String.valueOf(formattedSum + " pesos");
                
                String formattedSum1 = String.format("%.4f", sum1);
                String sumString1 = String.valueOf(formattedSum1 + " pesos");
                
                String usedAppliance = String.valueOf(tableValues.getRowCount() + " Appliances");
                
                totalSum ts = new totalSum(); 
                ts.dayEstimation.setText(sumString);
                ts.monthEstimation.setText(sumString1);
                ts.appliancesUsed.setText(usedAppliance);
                ts.setVisible(true);
}
    private void electricFan4electricFanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electricFan4electricFanActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Electric Fan");
        input.pack();
        input.setLocationRelativeTo(null);
    }//GEN-LAST:event_electricFan4electricFanActionPerformed

    private void airconSplit4airconSplitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airconSplit4airconSplitActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Aircon Split");
    }//GEN-LAST:event_airconSplit4airconSplitActionPerformed

    private void WashingMachine4WashingMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WashingMachine4WashingMachineActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Washing Machine");
    }//GEN-LAST:event_WashingMachine4WashingMachineActionPerformed

    private void airconWindow4airconWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airconWindow4airconWindowActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Aircon Window");
    }//GEN-LAST:event_airconWindow4airconWindowActionPerformed

    private void ecToaster4ecToasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecToaster4ecToasterActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Microwave Oven");
    }//GEN-LAST:event_ecToaster4ecToasterActionPerformed

    private void breadToaster4breadToasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breadToaster4breadToasterActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Bread Toaster");
    }//GEN-LAST:event_breadToaster4breadToasterActionPerformed

    private void ledBulb4ledBulbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ledBulb4ledBulbActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("LED Light Bulb");
    }//GEN-LAST:event_ledBulb4ledBulbActionPerformed

    private void blower4blowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blower4blowerActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Blower");
    }//GEN-LAST:event_blower4blowerActionPerformed

    private void electricKettle4electricKettleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electricKettle4electricKettleActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Electric Kettle");
    }//GEN-LAST:event_electricKettle4electricKettleActionPerformed

    private void electricIron4electricIronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electricIron4electricIronActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Electric Iron");
    }//GEN-LAST:event_electricIron4electricIronActionPerformed

    private void fridge4fridgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fridge4fridgeActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Fridge");
    }//GEN-LAST:event_fridge4fridgeActionPerformed

    private void airFryer4airFryerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airFryer4airFryerActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Air Fryer");
    }//GEN-LAST:event_airFryer4airFryerActionPerformed

    private void waterDispenser4waterDispenserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterDispenser4waterDispenserActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Water Dispenser");
    }//GEN-LAST:event_waterDispenser4waterDispenserActionPerformed

    private void riceCooker4riceCookerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riceCooker4riceCookerActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Rice Cooker");
    }//GEN-LAST:event_riceCooker4riceCookerActionPerformed

    private void electricStove4electricStoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electricStove4electricStoveActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Electric Stove");
    }//GEN-LAST:event_electricStove4electricStoveActionPerformed

    private void vacuumCleaner4vacuumCleanerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacuumCleaner4vacuumCleanerActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Vacuum Cleaner");
    }//GEN-LAST:event_vacuumCleaner4vacuumCleanerActionPerformed

    private void showerHeater4showerHeaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showerHeater4showerHeaterActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Shower Heater");
    }//GEN-LAST:event_showerHeater4showerHeaterActionPerformed

    private void humidifier4humidifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_humidifier4humidifierActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Humidifier");
    }//GEN-LAST:event_humidifier4humidifierActionPerformed

    private void blender4blenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blender4blenderActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Blender");
    }//GEN-LAST:event_blender4blenderActionPerformed

    private void iceMaker4iceMakerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iceMaker4iceMakerActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Ice Maker");
    }//GEN-LAST:event_iceMaker4iceMakerActionPerformed

    private void phone4phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone4phoneActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Phone");
    }//GEN-LAST:event_phone4phoneActionPerformed

    private void laptop4laptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laptop4laptopActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Laptop");
    }//GEN-LAST:event_laptop4laptopActionPerformed

    private void sandPress4sandPressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sandPress4sandPressActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Sandwich Press");
    }//GEN-LAST:event_sandPress4sandPressActionPerformed

    private void mosqKiller4mosqKillerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mosqKiller4mosqKillerActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Mosquito Killer");
    }//GEN-LAST:event_mosqKiller4mosqKillerActionPerformed

    private void ovenToaster4ovenToasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovenToaster4ovenToasterActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Oven Toaster");
    }//GEN-LAST:event_ovenToaster4ovenToasterActionPerformed

    private void electricOven4electricOvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electricOven4electricOvenActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Electric Oven");
    }//GEN-LAST:event_electricOven4electricOvenActionPerformed

    private void hairStraightener4hairStraightenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairStraightener4hairStraightenerActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Hair Straightener");
    }//GEN-LAST:event_hairStraightener4hairStraightenerActionPerformed

    private void Tablet4TabletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tablet4TabletActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Tablet");
    }//GEN-LAST:event_Tablet4TabletActionPerformed

    private void desktopPC4desktopPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desktopPC4desktopPCActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Portable Computer");
    }//GEN-LAST:event_desktopPC4desktopPCActionPerformed

    private void dtMonitor4dtMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtMonitor4dtMonitorActionPerformed
        InputForm input = new InputForm();
        input.setVisible(true);
        input.Appliance.setText("Monitor");
    }//GEN-LAST:event_dtMonitor4dtMonitorActionPerformed

    private void statsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsButtonActionPerformed
        TableModel tableModel = tableValues.getModel();

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            double sum = 0;
            String appliance = (String) tableModel.getValueAt(i, 0);
            String pricePerUse = (String) tableModel.getValueAt(i, 2);
            String pricePerUseRemoved = pricePerUse.replace(" pesos", "");
            double pricePerUseNew = Double.parseDouble(pricePerUseRemoved);
            sum += pricePerUseNew;
            
        dataset.addValue(sum, "Price (Day)", appliance);
        }
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            double sum = 0;
            String appliance = (String) tableModel.getValueAt(i, 0);
            String pricePerUse = (String) tableModel.getValueAt(i, 3);
            String pricePerUseRemoved = pricePerUse.replace(" pesos", "");
            double pricePerUseNew = Double.parseDouble(pricePerUseRemoved);
            sum += pricePerUseNew;
            
        dataset.addValue(sum, "Price (Month)", appliance);
        }
        JFreeChart chart = ChartFactory.createBarChart(
            "Appliance Usage Statistics",
            "",
            "Price (Pesos)",
            dataset,
            PlotOrientation.VERTICAL,
            true, true, false
        );
        
        CategoryPlot plot = chart.getCategoryPlot();

        BarRenderer renderer = (BarRenderer) plot.getRenderer();

        renderer.setSeriesPaint(0, new Color(147,225,111));
        renderer.setSeriesPaint(1, new Color(255,204,0));

        ChartFrame frame = new ChartFrame("Statistics", chart);
        frame.setPreferredSize(new java.awt.Dimension(560, 367));
        frame.setVisible(true);
        frame.setSize(450, 350);
        frame.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_statsButtonActionPerformed

    private void computeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeButtonActionPerformed
        getSum();
    }//GEN-LAST:event_computeButtonActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        MessageFormat header = new MessageFormat("Appliance Usage Table");
        MessageFormat footer = new MessageFormat("");
        try {
            PrintRequestAttributeSet set = new HashPrintRequestAttributeSet();
            set.add(OrientationRequested.PORTRAIT);
            tableValues.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, set, true);
        } catch (java.awt.print.PrinterException e) {
            JOptionPane.showMessageDialog(null, "\n" + "Failed" + "\n" + e);
        }
    }//GEN-LAST:event_exportButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        PressStart ps = new PressStart();
        ps.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        try {
        DefaultTableModel model = (DefaultTableModel)tableValues.getModel();
        int selectedRowIndex = tableValues.getSelectedRow();
        model.removeRow(selectedRowIndex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Please Select a Row.");
        }
        
    }//GEN-LAST:event_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Clear;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JLabel LogoLabel1;
    private javax.swing.JButton Tablet4;
    private javax.swing.JButton WashingMachine4;
    private javax.swing.JButton airFryer4;
    private javax.swing.JButton airconSplit4;
    private javax.swing.JButton airconWindow4;
    private javax.swing.JButton blender4;
    private javax.swing.JButton blower4;
    private javax.swing.JButton breadToaster4;
    private javax.swing.JButton computeButton;
    private javax.swing.JButton desktopPC4;
    private javax.swing.JButton dtMonitor4;
    private javax.swing.JButton ecToaster4;
    private javax.swing.JButton electricFan4;
    private javax.swing.JButton electricIron4;
    private javax.swing.JButton electricKettle4;
    private javax.swing.JButton electricOven4;
    private javax.swing.JButton electricStove4;
    private javax.swing.JButton exportButton;
    private javax.swing.JButton fridge4;
    private javax.swing.JButton hairStraightener4;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton humidifier4;
    private javax.swing.JButton iceMaker4;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton laptop4;
    private javax.swing.JButton ledBulb4;
    private javax.swing.JButton mosqKiller4;
    private javax.swing.JButton ovenToaster4;
    private javax.swing.JButton phone4;
    private javax.swing.JButton riceCooker4;
    private javax.swing.JButton sandPress4;
    private javax.swing.JButton showerHeater4;
    private javax.swing.JButton statsButton;
    public static javax.swing.JTable tableValues;
    private javax.swing.JButton vacuumCleaner4;
    private javax.swing.JButton waterDispenser4;
    // End of variables declaration//GEN-END:variables
}
