/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HPage;

/**
 *
 * @author yzer
 */
public class totalSum extends javax.swing.JFrame {

    /**
     * Creates new form totalSum
     */
    public totalSum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LogoLabel1 = new javax.swing.JLabel();
        dayEstimation = new javax.swing.JLabel();
        monthEstimation = new javax.swing.JLabel();
        appliancesUsed = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(250, 250, 205));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Press Start 2P", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Price Estimations");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 483, 40));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Press Start 2P", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total Estimation Today");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 270, 30));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Press Start 2P", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Appliances Used Today");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setMaximumSize(new java.awt.Dimension(268, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(268, 16));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(268, 16));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 260, 30));

        LogoLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HPage/PicturesAssets/logo small.png"))); // NOI18N
        LogoLabel1.setFocusable(false);
        jPanel1.add(LogoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        dayEstimation.setBackground(new java.awt.Color(255, 204, 0));
        dayEstimation.setFont(new java.awt.Font("Press Start 2P", 0, 12)); // NOI18N
        dayEstimation.setForeground(new java.awt.Color(0, 0, 0));
        dayEstimation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dayEstimation.setText("0.0000 pesos");
        dayEstimation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dayEstimation.setMaximumSize(new java.awt.Dimension(88, 16));
        dayEstimation.setMinimumSize(new java.awt.Dimension(88, 16));
        dayEstimation.setOpaque(true);
        dayEstimation.setPreferredSize(new java.awt.Dimension(88, 16));
        jPanel1.add(dayEstimation, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 530, 40));

        monthEstimation.setBackground(new java.awt.Color(255, 204, 0));
        monthEstimation.setFont(new java.awt.Font("Press Start 2P", 0, 12)); // NOI18N
        monthEstimation.setForeground(new java.awt.Color(0, 0, 0));
        monthEstimation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        monthEstimation.setText("0.0000 pesos");
        monthEstimation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        monthEstimation.setOpaque(true);
        jPanel1.add(monthEstimation, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 530, 40));

        appliancesUsed.setBackground(new java.awt.Color(255, 204, 0));
        appliancesUsed.setFont(new java.awt.Font("Press Start 2P", 0, 12)); // NOI18N
        appliancesUsed.setForeground(new java.awt.Color(0, 0, 0));
        appliancesUsed.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        appliancesUsed.setText("0 Appliances");
        appliancesUsed.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        appliancesUsed.setOpaque(true);
        jPanel1.add(appliancesUsed, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 530, 40));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Press Start 2P", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Estimation this Month");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setMaximumSize(new java.awt.Dimension(268, 16));
        jLabel4.setMinimumSize(new java.awt.Dimension(268, 16));
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(268, 16));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 330, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(totalSum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(totalSum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(totalSum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(totalSum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new totalSum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoLabel1;
    public javax.swing.JLabel appliancesUsed;
    public javax.swing.JLabel dayEstimation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel monthEstimation;
    // End of variables declaration//GEN-END:variables
}
